CREATE TABLE SupplyPoints (Sprn STRING PRIMARY KEY UNIQUE NOT NULL, FuelType STRING NOT NULL);

CREATE TABLE Meters (SerialNumber STRING PRIMARY KEY UNIQUE NOT NULL, FuelType STRING NOT NULL, MeterType STRING, Status STRING);
CREATE UNIQUE INDEX Idx_Meters ON Meters (SerialNumber ASC);

CREATE TABLE MeterRegisters (StartDate STRING PRIMARY KEY NOT NULL, EndDate STRING, FuelType STRING NOT NULL, Id STRING, TimingCategory STRING, UnitOfMeasurement STRING);
CREATE UNIQUE INDEX Idx_MeterRegisters ON MeterRegisters (StartDate ASC);